backend:
  name: github
  repo: Destinyjoshua/JoshuaEze
  branch: main
  auth_type: implicit
  client_id: Ov23li4BVhRipA9I7F6Q

site_url: https://joshuaeze.com
base_url: https://joshuaeze.com

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Framework", value: "FRAMEWORK" }
          - { label: "African Context", value: "AFRICAN CONTEXT" }
          - { label: "Personal", value: "PERSONAL" }
          - { label: "Big Picture", value: "BIG PICTURE" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }